---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bazarr
      version: 9.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v0.9.5
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.testkube.cardboardbox.be/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.testkube.cardboardbox.be/oauth2/start"
        hosts:
        - host: bazarr.testkube.cardboardbox.be
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - bazarr.testkube.cardboardbox.be
    env:
      TZ: Europe/Brussels
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config
      media:
        enabled: true
        existingClaim: nfs-media-pvc
    resources:
      requests:
        memory: 512Mi
        cpu: 150m
      limits:
        memory: 512Mi
        cpu: 500m
