---
fail_fast: false
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.0
    hooks:
      - id: yamllint
        args:
          - -c
          - ".github/yamllint.config.yaml"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck
        language: script
        args: [--severity=error]
        additional_dependencies: []
  - repo: https://github.com/sirosen/fix-smartquotes
    rev: 0.2.0
    hooks:
      - id: fix-smartquotes
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint
        name: Run markdownlint
        description: Lint markdown files
        entry: markdownlint -c .github/.markdownlint.yaml
  - repo: local
    hooks:
      - id: check-sops-secrets
        name: Check for unencrypted SOPS secrets
        entry: ./hacks/check-sops-secrets-hook.sh
        language: script
        files: \.(ya?ml)$
