---
# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # Encrypt secret files with GPG key
  - encrypted_regex: '^(data|stringData)$'
    pgp: 'E2D99EA2EE98E4677A00C64769B7868093023FE3'
