---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: oauth2-proxy
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
  - name: dex
    namespace: kube-system
  values:
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v7.1.1
    replicaCount: 2
    ingress:
      enabled: true
      path: /oauth2
      hosts:
      - "auth.testkube.cardboardbox.be"
      tls:
      - hosts:
        - "auth.testkube.cardboardbox.be"
    extraArgs:
      provider: oidc
      oidc-issuer-url: "https://dex.testkube.cardboardbox.be"
      skip-provider-button:
      pass-authorization-header:
      email-domain: "*"
      cookie-domain: ".testkube.cardboardbox.be"
      whitelist-domain: ".testkube.cardboardbox.be"
  valuesFrom:
  - kind: Secret
    name: "oauth2-proxy-helm-values"
