---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-linode
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: ./deploy/cert-manager-webhook-linode
      version: v0.1.0
      sourceRef:
        kind: GitRepository
        name: cert-manager-webhook-linode-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: slicen/cert-manager-webhook-linode
      tag: v0.1.0
    api:
      groupName: acme.testkube.cardboardbox.be
