---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: testkube-cardboardbox-be
  namespace: kube-system
spec:
  secretName: kube-cardboardbox-be-tls
  issuerRef:
    name: linode-letsencrypt-prod
    kind: ClusterIssuer
  commonName: "testkube.cardboardbox.be"
  dnsNames:
  - "testkube.cardboardbox.be"
  - "*.testkube.cardboardbox.be"
