---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- flux-extra/discord
- flux-extra/github
- flux-extra/helm-repos
- infra.yaml
- crds.yaml
- namespaces.yaml
