kind: Secret
apiVersion: v1
metadata:
    name: discord-webhook-url
    namespace: flux-system
    creationTimestamp: null
data:
    address: ENC[AES256_GCM,data:GJvfqQ+osBwTwlVAYLs/vKkJawbggcjeZJJIq5eXezW1I5vJG/xYHLd8VO+3cpo85MFWKJl1iCrQVTSd/uwquVddGVupguZNKnHYxWlHlFQ84TJfgcHqoTWFcJGG2ONA4reM5pZ4zJR5gWyTOs0TwN7SePI+Y2oOfRLku2XuKya3yhNLCLrEVY4qxwMTbKW7v9Cd/RetvLbrHxMUGW5raA==,iv:mdr9vvy5SL3JwcdnyltxO+5gOXgp9cGo3LIppQBBJp8=,tag:9/LBHoYEiEVrJqsOGiHhfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-03-31T13:57:22Z"
    mac: ENC[AES256_GCM,data:EqIQcL3ToM0wWowaCEFJoaviQzPewcY90nY7WJ1D9BF9898mf5kXqJwXOCQqhjIo4behrEsG2Hy4kswvUwhX19GRv7WeFxf/G0DHzK/uzmOIg3bLk3hgHwHqrCwEa3vGG7OUNp5TTlR3ZebJiDVvyU1O25e1/giTkrb7yfb9Yho=,iv:V0ZfFCEHLDqm7eTOCfijBkWVG0PjJPZgmJk3dwHQs/Y=,tag:Vui1QrTkojrUFAYKxoVfNg==,type:str]
    pgp:
        - created_at: "2021-03-31T13:57:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6IKXLsgzTh+ARAAofFc+u2O1BAdFuz0OBbsmfEJOlLDP8SGBBsvMO2Mc+Eb
            g56ptIOeGk6bOeFz/hfDQcbzD+i1rouj0Ls3tA7jcdO2uERlVI2COD5Y4FtkYWan
            v/4fW6KLzuG7r4/svL1dvWm4Blt2axPC8DHl8coqOhyMk5a3nQJCL74xok2Z2fG5
            r54+v7qpcuq2gT1odMKEVC5IRe2YsZXQdeH6s5RxZ6PhaNN0g5S0olOg019Tl5eb
            ZAJH6Z/5MKDj1dzs0nzbEUfM7HlLUIUpBDJBFTHYRrKxvKowjAeBrJoiUYenpgCK
            BgGxYZQCi74uJuSuE7iqvmP7XOT+iFnDxYyy+o05RXI8zItKrFr5DINLXHXEBWQm
            Hv/IHhW4aOBkrA/Y+nCicVj2a0jNBqcnKV/pxJR7adOUlpESkCnIrIBzZ5NE6d5y
            DRm1xKUUxGwH5inTeKhIcblExT4cVsuBHsQw8KUDr5o2cryZCvDaLHEn9m4ylDAb
            M+KTi653gEOAj4C4sKptZ9YVpr3Ne2qARgTfNYqQdTjyfVoU3DKr3NKu52DKyod7
            F8c2JKI16qo+KqZGACrEojB8iHWF/gmw9hVd0Vyg49j8EMdudFCuFGAL9fBb/r+f
            Ak50Ew3W7s4sinb5OTW4Cadn6G2zEeTDstu8y9OkkcbKz1qbwdjGcbg0h1wBAazS
            5gGIq/bLVAB/kSJwuAF+07NNsLfmc51FgnNYFBIi71BVSNoOmD9l+q1TodKSxNI5
            nITBbE7wWMrekSyhDC1X0uzkia+BBQqcdy/TWlsN5hQckeJ1H4GMAA==
            =0sn3
            -----END PGP MESSAGE-----
          fp: E2D99EA2EE98E4677A00C64769B7868093023FE3
        - created_at: "2021-03-31T13:57:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5YRaKofaz9CAQ//dpof4sBDjfZo5wdtuUmCit7lWs85Gj3FVkZaN5Bvx9x0
            JQ4BvkM9WiEdX+EK8mg+IMP1OpudPsFYwuXZ0Zlc3/fnair4TZ+Ol0K5yfMJiPM0
            zFbvAz/h4CmWOoyCtFISIuMyg3/6uy8etuPkrOc5qn/+GtdatRsuBdrVZgEdvAGM
            Ymzf+g2W+KXjrQDsoIL4fo1FYCvUhT+tlG4Pce6JhHHddlZULEhGW5DzLocI0/2e
            iUt40eIAW2oG08saXM4dMlE42c2c5KHGT01CfqC/jkKCM4LZECCRSyzNlF1VDyLO
            NZiEVGyi6jeeF3Lt7j4cUtnnsQRT2mT27MbYu2Q4O+xhhY2wQkdlnqgVDU4FbI8g
            EXu5mvLOyv1Tc+ijHSOth1CUmw97Cg86XPZSN02ewSpzAGKjSzmO8aVcWnCD+RDR
            dXSi56FCaP3RsQ/Zp4upbPfOHKzXKjqHZwy4VVOEEZWbsyZmtYaRo7yDeGLzybT+
            51feN/QN5H9c+G3hYQBaniRg8LHZMbcaHd8DeVOmsXMvu3hqwiF4XOPK3dT6xY7K
            euzSb5LICzj6qEyM/vCUAOU+u9XOE4K7frbdIZxGdEhMlT6vnkZTRIXdeYOPdqoT
            msdqYCV8aZ8tdx1qA/YQzhkrfuoXiElS3AbijHezTt+GPkKnY1D10MNdLYj5fenS
            XgHr7gS3FhRT8RScWejr+zQ8sNOCtw5pS2KW0LQkvYLjFCaRsFM//MFTUOf/FG8+
            h2nJSlZWPVVK7085dB2l2WUMovr1uI8kVEzwi7kcscBlcGxQR2E0+QGvonPQc9M=
            =R1VD
            -----END PGP MESSAGE-----
          fp: 9D499331E77AB71942B0BD98C18E05E9EFD35DA6
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
