---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: kube-system
spec:
  releaseName: dex
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.dexidp.io
      chart: dex
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: dex-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: coredns
      namespace: kube-system
  values:
    image:
      repository: dexidp/dex
      tag: v2.28.1
    env:
      KUBERNETES_POD_NAMESPACE: kube-system
    ingress:
      enabled: true
      hosts:
        - host: dex.testkube.cardboardbox.be
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - dex.testkube.cardboardbox.be
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 250Mi
  valuesFrom:
    - kind: Secret
      name: "dex-helm-values"
      optional: false
