---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager/cert-manager/helm-release.yaml
- cert-manager/cert-manager/issuers.yaml
- cert-manager/cert-manager-webhook-linode/helm-release.yaml
- cert-manager/cert-manager-webhook-linode/linode-credentials.enc.yaml
- flux-system/gotk-monitoring.yaml
- kube-system/coredns/helm-release.yaml
- kube-system/dex/helm-release.yaml
- kube-system/dex/dex-helm-values.enc.yaml
- kube-system/etcd/helm-release.yaml
- kube-system/external-dns/helm-release.yaml
- kube-system/ingress-nginx/certificate.yaml
- kube-system/ingress-nginx/helm-release.yaml
- kube-system/oauth2-proxy/oauth2-proxy-helm-values.enc.yaml
- kube-system/oauth2-proxy/helm-release.yaml
- longhorn-system/longhorn/helm-release.yaml
- monitoring/grafana/helm-release.yaml
- monitoring/grafana/grafana-helm-values.enc.yaml
- monitoring/kube-prom-stack/helm-release.yaml
- system-upgrade/system-upgrade-controller/system-upgrade-controller.yaml
