---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bitnami-charts.yaml
- coredns-charts.yaml
- cert-manager-linode-webhook-charts-git.yaml
- grafana-charts.yaml
- ingress-nginx-charts.yaml
- jetstack-charts.yaml
- k8s-at-home-charts.yaml
- longhorn-charts.yaml
- node-feature-discovery-charts.yaml
- prometheus-community-charts.yaml
