---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.2.0
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
      interval: 5m
  values:
    installCRDs: false
    webhook:
      enabled: true
    extraArgs:
    - --dns01-recursive-nameservers=1.1.1.1:53
    - --dns01-recursive-nameservers-only
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        prometheusInstance: monitoring
